version: '2'

services:
  nginx:
    build: ../nginx/.
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - 'web'
  web:
    build: ../.
    image: online-meeting
    command: './online-meeting'
    working_dir: /app/user
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/online-meeting
    depends_on:
      - db

  migrate:
    build: ../.
    image: online-meeting
    command: bash -c 'while ! nc -q 1 db 3306 </dev/null; do sleep 1; done && kgen migrate up'
    working_dir: /app/user
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/online-meeting
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: online-meeting
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - '/home/ubuntu/mysql:/var/lib/mysql'
